let conf = [
  {
    "srcImg":"./Img/google_crop.png",
    "dstUrl":"https://www.google.com"
  },
  {
    "srcImg":"./Img/facebook_crop.png",
    "dstUrl":"https://www.facebook.com"
  },
  {
    "srcImg":"./Img/wikipedia_crop.png",
    "dstUrl":"https://it.wikipedia.org/wiki/Pagina_principale"
  },
  {
    "srcImg":"./Img/yt_crop.png",
    "dstUrl":"https://www.youtube.com"
  },
  {
    "srcImg":"./Img/dotabuff_crop.png",
    "dstUrl":"https://www.dotabuff.com/players/230443374"
  },
  {
    "srcImg":"./Img/lamma_crop.png",
    "dstUrl":"http://www.lamma.rete.toscana.it/meteo/bollettini-meteo/toscana"
  },
  {
    "srcImg":"./Img/repubblica_crop.png",
    "dstUrl":"http://www.repubblica.it/"
  },
  {
    "srcImg":"./Img/amazon_crop.png",
    "dstUrl":"https://www.amazon.it/"
  },
  {
    "srcImg":"./Img/unipi_crop.png",
    "dstUrl":"https://www.di.unipi.it/it/"
  },
  {
    "srcImg":"./Img/w3c_crop.png",
    "dstUrl":"https://www.w3schools.com/"
  },
  {
    "srcImg":"./Img/maps_crop.png",
    "dstUrl":"https://www.google.it/maps/@43.8139492,10.4994844,12.33z"
  },
  {
    "srcImg":"./Img/mail_crop.png",
    "dstUrl":"https://mail.google.com/mail/u/0/#inbox"
  },
  {
    "srcImg":"./Img/ebay_crop.png",
    "dstUrl":"https://www.ebay.it/"
  },
  {
    "srcImg":"./Img/wapp_crop.png",
    "dstUrl":"https://web.whatsapp.com/"
  },
  {
    "srcImg":"./Img/telegram_crop.png",
    "dstUrl":"https://web.telegram.org/"
  },
  {
    "srcImg":"./Img/speedtest_crop.png",
    "dstUrl":"http://beta.speedtest.net/it"
  },
  {
    "srcImg":"./Img/twitch_crop.png",
    "dstUrl":"https://www.twitch.tv/dota2"
  },
  {
    "srcImg":"./Img/arch_crop.png",
    "dstUrl":"https://www.archlinux.org/"
  },
  {
    "srcImg":"./Img/libgen_crop.png",
    "dstUrl":"en.lib.rus.ec"
  },
  {
    "srcImg":"./Img/steam_crop.png",
    "dstUrl":"http://store.steampowered.com/?l=italian"
  },
  {
    "srcImg":"./Img/thing_crop.png",
    "dstUrl":"https://www.thingiverse.com/"
  },
  {
    "srcImg":"./Img/translate_crop.png",
    "dstUrl":"https://translate.google.it/"
  },
  {
    "srcImg":"./Img/mps_crop.png",
    "dstUrl":"https://ib.mps.it/web/ib/login"
  },
  {
    "srcImg":"./Img/node_crop.png",
    "dstUrl":"https://nodejs.org/api/"
  },
  {
    "srcImg":"./Img/qt_crop.png",
    "dstUrl":"http://doc.qt.io/"
  },
  {
    "srcImg":"./Img/sd_crop.png",
    "dstUrl":"https://slashdot.org/"
  },
  {
    "srcImg":"./Img/instructables_crop.png",
    "dstUrl":"https://www.instructables.com/"
  },
  {
    "srcImg":"./Img/github_crop.png",
    "dstUrl":"https://github.com/teo666"
  },
  {
    "srcImg":"./Img/allaboutcircuits_crop.png",
    "dstUrl":"https://www.allaboutcircuits.com/"
  },
  {
    "srcImg":"./Img/osm_crop.png",
    "dstUrl":"https://www.openstreetmap.org/#map=9/43.7889/10.5304&layers=C/"
  },
  {
    "srcImg":"./Img/fs_crop.png",
    "dstUrl":"http://www.trenitalia.com/"
  }
];